

using System;
using System.Reflection;
using System.Runtime.InteropServices;

// 
// Assemblyinfo.cs is autogenerated. Any changes made manually will be lost
// the next time this code is regenerated. 
// If you want to change assembly information edit
// Assemblyinfo.tt
// 

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.

[assembly: AssemblyTitle("RobotManager")]
[assembly: AssemblyDescription("Server / Management Application For Webots Robots")]

#if DEBUG
	[assembly: AssemblyConfiguration("Debug")]
#else
    [assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyCompany("None")]
[assembly: AssemblyProduct("Webots")]
[assembly: AssemblyCopyright("None© 2024")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("09b89691-2633-489d-a009-d3d33b4decb0")]

[assembly: AssemblyVersion("24.3.17.64285")]
[assembly: AssemblyFileVersion("24.3.17.64285")]

